#!/usr/bin/env bash

# Configuration
base_dir=${NAVIGATOR_BASE_DIR:-$HOME/github} # Default to $HOME/github if NAVIGATOR_BASE_DIR is unset
navigator_mode=${NAVIGATOR_MODE:-tmux} # Default to tmux mode if NAVIGATOR_MODE is unset
navigator_structure=${NAVIGATOR_STRUCTURE:-workspace} # Options: "unsorted", "workspace", "workspace_src"

case $navigator_structure in
    unsorted)
        # For unsorted packages, list all directories under the base directory and show full paths
        find_depth=(-mindepth 1 -maxdepth 2 -type d)
        awk_field='{print $0}'
        ;;
    workspace_src)
        # For WORKSPACE/src/PROJECT structure
        find_depth=(-mindepth 2 -maxdepth 3 -type d -path "*/src/*")
        awk_field='{print $(NF)"("$(NF-2)")"}'
        ;;
    workspace)
        # For WORKSPACE/PROJECT structure
        find_depth=(-mindepth 2 -maxdepth 2 -type d)
        awk_field='{print $(NF)"("$(NF-1)")"}'
        ;;
    *)
        echo "Invalid NAVIGATOR_STRUCTURE: $navigator_structure. Must be 'unsorted', 'workspace', or 'workspace_src'."
        exit 1
        ;;
esac

selected=$(find "$base_dir" "${find_depth[@]}" | awk -F '/' "$awk_field" | sort -u | fzf)

if [[ -z $selected ]]; then
    echo "No selection made."
    [[ $navigator_mode == "tmux" ]] && exit 0 || return 0
fi

if [[ "$navigator_structure" == "unsorted" ]]; then
    package_path="$selected"
else
    package=$(echo "$selected" | sed -E 's|\((.*)\)||' | xargs)
    project=$(echo "$selected" | sed -E 's|.*\((.*)\)|\1|' | xargs)

    if [[ "$navigator_structure" == "workspace_src" ]]; then
        package_path="$base_dir/$project/src/$package"
    else
        package_path="$base_dir/$project/$package"
    fi
fi

if [[ ! -d $package_path ]]; then
    echo "Error: Package directory not found: $package_path"
    exit 1
fi

if [[ "$navigator_mode" == "tmux" ]]; then
    # TMUX
    session_name=$(echo "${package_path}" | tr / _ | tr . _)
    tmux_running=$(pgrep tmux)

    if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
        tmux new-session -s "$session_name" -c "$package_path"
        exit 0
    fi

    if ! tmux has-session -t="$session_name" 2> /dev/null; then
        tmux new-session -ds "$session_name" -c "$package_path"
    fi

    tmux switch-client -t "$session_name"
else
    # CD
    cd "$package_path" && clear || {
        echo "Failed to change directory to: $package_path"
        exit 1
    }
fi
